#!/bin/bash
set -e

echo "=========================================="
echo "  CampusMatch Production Setup Guide"
echo "=========================================="
echo ""
echo "This script walks you through setting up all"
echo "production services. You'll need:"
echo "  - A web browser"
echo "  - A credit card (free tiers available)"
echo "  - ~15 minutes"
echo ""

# ── 1. RESEND (Email) ──────────────────────────────────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  STEP 1/6: RESEND (Email Service)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Open: https://resend.com"
echo "  2. Sign up with your email"
echo "  3. Go to API Keys → Create Key"
echo "  4. Copy the key (starts with 're_')"
echo "  5. Optional: Add your domain for custom sender"
echo ""
echo "  Free tier: 100 emails/day, 3000/month"
echo ""
read -p "  Paste your RESEND_API_KEY (or press Enter to skip): " RESEND_KEY
echo ""

# ── 2. CLOUDFLARE R2 (File Storage) ────────────────────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  STEP 2/6: CLOUDFLARE R2 (File Storage)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Open: https://dash.cloudflare.com/sign-up"
echo "  2. Sign up (free, no credit card needed)"
echo "  3. Go to R2 Object Storage → Create Bucket"
echo "  4. Name it 'campusmatch-uploads'"
echo "  5. Go to R2 → Manage R2 API Tokens → Create Token"
echo "  6. Permissions: Object Read & Write"
echo "  7. Copy: Access Key ID + Secret Access Key"
echo "  8. Go to Bucket → Settings → Public Access"
echo "  9. Enable Public Access → copy the Public URL"
echo ""
echo "  Free tier: 10GB storage, 10M reads/month"
echo ""
read -p "  Paste S3_ENDPOINT (or Enter to skip, leave blank): " S3_ENDPOINT
read -p "  Paste S3_BUCKET (default: campusmatch-uploads): " S3_BUCKET
S3_BUCKET=${S3_BUCKET:-campusmatch-uploads}
read -p "  Paste S3_PUBLIC_URL (e.g. https://pub-xxx.r2.dev): " S3_PUBLIC_URL
read -p "  Paste S3_ACCESS_KEY_ID: " S3_ACCESS_KEY
read -p "  Paste S3_SECRET_ACCESS_KEY: " S3_SECRET_KEY
echo ""

# ── 3. REDIS (Optional - for persistent rate limits) ───────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  STEP 3/6: UPSTASH REDIS (Optional)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Open: https://upstash.com"
echo "  2. Sign up with GitHub/Google"
echo "  3. Create Database → Choose 'Global' region"
echo "  4. Copy the REST URL"
echo ""
echo "  Free tier: 10K commands/day"
echo "  (App works without Redis, uses in-memory)"
echo ""
read -p "  Paste REDIS_URL (or press Enter to skip): " REDIS_URL
echo ""

# ── 4. DATABASE (PostgreSQL) ───────────────────────────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  STEP 4/6: DATABASE (Neon PostgreSQL)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Open: https://neon.tech"
echo "  2. Sign up with GitHub/Google"
echo "  3. Create Project → Name: 'campusmatch'"
echo "  4. Copy the Connection String (pooled)"
echo "  5. It looks like: postgresql://user:pass@ep-xxx.us-east-2.aws.neon.tech/dbname"
echo ""
echo "  Free tier: 0.5GB storage, always-on compute"
echo ""
read -p "  Paste DATABASE_URL: " DATABASE_URL
echo ""

# ── 5. JWT SECRET ──────────────────────────────────────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  STEP 5/6: JWT SECRET"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
JWT_SECRET=$(openssl rand -hex 32)
echo "  Generated secure JWT_SECRET: ${JWT_SECRET:0:16}..."
echo ""

# ── 6. HOSTING (Railway) ──────────────────────────────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  STEP 6/6: HOSTING (Railway)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Open: https://railway.app"
echo "  2. Sign up with GitHub"
echo "  3. New Project → Deploy from GitHub Repo"
echo "  4. Select your CampusMatch repo"
echo "  5. Add these Environment Variables:"
echo ""
echo "  (See .env.production below for all vars)"
echo ""
echo "  Railway handles:"
echo "    - HTTPS (automatic)"
echo "    - Custom domains"
echo "    - Auto-deploy on push"
echo ""
echo "  Free tier: $5 credit/month (enough for small app)"
echo ""

# ── WRITE .env.production ───────────────────────────────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Writing .env.production..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

cat > artifacts/api-server/.env.production << EOF
# CampusMatch Production Environment
# Generated by setup script

# ── Database ──────────────────────────────────────────────────────────
DATABASE_URL=${DATABASE_URL:-postgresql://user:password@host:5432/campusmatch}

# ── Security ──────────────────────────────────────────────────────────
JWT_SECRET=${JWT_SECRET:-$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | xxd -p | tr -d '\n' | head -c 64)}

# ── Email ─────────────────────────────────────────────────────────────
RESEND_API_KEY=${RESEND_KEY:-}
RESEND_FROM=onboarding@campusmatch.in

# ── CORS ──────────────────────────────────────────────────────────────
ALLOWED_ORIGINS=https://campusmatch.in

# ── Storage ───────────────────────────────────────────────────────────
STORAGE_DRIVER=${S3_ACCESS_KEY:+s3}
STORAGE_DRIVER=\${STORAGE_DRIVER:-local}

S3_ENDPOINT=${S3_ENDPOINT:-}
S3_REGION=auto
S3_BUCKET=${S3_BUCKET:-}
S3_PUBLIC_URL=${S3_PUBLIC_URL:-}
S3_ACCESS_KEY_ID=${S3_ACCESS_KEY:-}
S3_SECRET_ACCESS_KEY=${S3_SECRET_KEY:-}

# ── Redis ─────────────────────────────────────────────────────────────
REDIS_URL=${REDIS_URL:-}

# ── Google OAuth ──────────────────────────────────────────────────────
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# ── Node ──────────────────────────────────────────────────────────────
NODE_ENV=production
PORT=3000
EOF

echo ""
echo "=========================================="
echo "  ✅ SETUP COMPLETE"
echo "=========================================="
echo ""
echo "  Next steps:"
echo "  1. Push your code to GitHub"
echo "  2. Deploy on Railway/Fly.io/Render"
echo "  3. Add env vars to hosting provider"
echo "  4. (Optional) Connect custom domain"
echo ""
echo "  Quick deploy command:"
echo "    git add . && git commit -m 'production setup' && git push"
echo ""
